version: 2.1
orbs:
  gradle: circleci/gradle@2.2.0
  android: circleci/android@2.1.2

jobs:
  build-test-sonar:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.05.1
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Wrapper
          command: ./gradlew wrapper
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lib:testDebugUnitTest lib:jacocoTestReport
#      - run:
#          name: Upload Coverage Report to SonarCloud
#          command: ./gradlew sonarqube
      - store_test_results:
          path: lib/build/test-results/testDebugUnitTest
  deploy-to-sonatype:
    docker:
      - image: cimg/android:2023.05-browsers
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Wrapper
          command: ./gradlew wrapper
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "lib/build.gradle" }}
      - run:
          name: Inject Maven signing key
          command: |
            chmod +x signing.sh
            ./signing.sh
      - run:
          name: Publish to Maven
          command: ./gradlew assemble publish
workflows:
  build-test-sonar-publish:
    jobs:
      - build-test-sonar:
          context:
            - SonarCloud
            - maven-sign
            - mobile
      - deploy-to-sonatype:
          name: Build, run tests, sonar and push to maven staging
          requires:
            - build-test-sonar
          context:
            - SonarCloud
            - maven-sign
            - mobile
          filters:
            branches:
              only:
                - staging
